# Generated by Django 4.0.5 on 2022-06-22 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='category',
            field=models.CharField(default='Category', max_length=50),
        ),
        migrations.AddField(
            model_name='resolution',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='resolution',
            name='source_link',
            field=models.CharField(default='google.com', max_length=200),
        ),
    ]
