# Generated by Django 4.0.5 on 2022-06-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_resolution_category_resolution_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolution',
            old_name='source_link',
            new_name='link',
        ),
    ]
