# Generated by Django 4.0.5 on 2022-07-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_rename_source_link_resolution_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedResolution',
            fields=[
                ('resolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapping.resolution')),
                ('result', models.BooleanField()),
            ],
            bases=('scrapping.resolution',),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('party', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=20)),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.representative')),
                ('voted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping.extendedresolution')),
            ],
        ),
    ]
